[package]
name = "hyper"
version = "0.1.0"
edition = "2021"

[lib]
name = "hyper"
path = "lib.rs"

[features]
default = ["deno"]

deno = ["tokio", "deno_core", "deno_ast"]

[build-dependencies.deno_core]
version = "0.174"
optional = true

[dependencies.tokio]
version = "1.19"
features = ["full"]
optional = true

[dependencies.deno_core]
version = "0.174"
optional = true

[dependencies.deno_ast]
version = "0.22.0"
features = [
    "transpiling"
]
optional = true 

[dependencies]
reqwest = "0.11"
